# WINDOWS EXAMPLE: C:\Users\Son Vo\AppData\Local\chia-blockchain\app-1.2.3\resources\app.asar.unpacked\daemon\chia.exe
# LINUX EXAMPLE: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chia
chia_location: C:\Users\lam-son\AppData\Local\chia-blockchain\app-1.2.3\resources\app.asar.unpacked\daemon\chia.exe
plots_path: E:\Temp\final\
report_output_file: output.txt
health_point: 0.7